# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotedby', models.CharField(max_length=1000)),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otherquotes', models.ManyToManyField(related_name='otherquotes', to='app_login.User')),
                ('userquotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userquotes', to='app_login.User')),
            ],
        ),
    ]
